### ISSUE TITLE
Epic: Final Refinments to N5 Export

### ISSUE THREAD

**Issue by AvocadoMoon** [virtualcell/vcell-fiji#31]
### Motivation
The N5 export process works, but it requires a learning curve to understand arbitrary bugs or lack of features. Such an export will be hesitantly used because it is not a tool which works with the user.

### Completion Criteria
A tool that is able to export exactly what the user desires, have a way to view all exports comfortably, and open in ImageJ easily.

## Stories/Tasks
- [x] https://github.com/virtualcell/vcell/issues/1163
- [x] virtualcell/vcell#1181
- [x] virtualcell/vcell-fiji#34
- [x] virtualcell/vcell-fiji#18 
- [x] virtualcell/vcell-fiji#8 
- [ ] virtualcell/vcell#1188
- [x] Dan's Revise of the VCell Export Table
- [x] #37
- [ ] #40
- [x] Pop up or something similar for user exporting to let them know export link should be copied
- [x] #38

### Future
- https://github.com/virtualcell/vcell/issues/984
- virtualcell/vcell-fiji#9 
- https://github.com/virtualcell/vcell/issues/1330
- [x] Search function to export table

### VCell Quirks 
- The export messages within the last `x` amount of time get replayed to the client
- Post processed variables which are being exported don't show progress of export in VCell client

### Previous Epic
- https://github.com/virtualcell/vcell-fiji/issues/11

**Comment by danv61** [comment]
We should add a "Delete" button to delete selected rows (exports).  That table may get busy quickly if the user exports a lot
We should implement the Search feature (which is now disable) to at least a basic search and filter through model / app / sim names.
