### ISSUE TITLE
Dataset Query Parameter

### ISSUE THREAD

**Issue by AvocadoMoon** [virtualcell/vcell-fiji#32]
### Problem
Having each export be tied to a dataset within an N5 file is great for file structure organization, but, it can be confusing for end users who believe their export is the N5 file itself.

### Solution
Put the dataset name for the export created as a query parameter, that way it can be read and the user never needs to know about the hierarchical structure of N5.

### Tasks

- [ ] Remove mentions of "Dataset" in N5 export settings
- [ ] When creating the link add the dataset name as a query parameter
- [ ] Interpret the query parameter in the IJ plugin
