### ISSUE TITLE
Epic: Data Reduction

### ISSUE THREAD

**Issue by AvocadoMoon** [virtualcell/vcell-fiji#57]
### Problem
Ann and other ImageJ users would want to perform some light image manipulation within ImageJ, then to export their now reformed Images into a CSV for analysis.

### Solution
Give users a GUI that allows for simple data reduction using statistical functions, which will be applied to both lab data and sim data, then to export this data in a CSV which users can do their analysis in.

### Tasks

- [x] Create data reduction GUI
- [x] Function that can normalize the entire Image based on some given time points
- [x] Function that can normalize ROI's based on some given time points
- [x] Status indication of data reduction/CSV export
- [x] Force only data reduction to occur, or implement simulation loading tags
- [x] Create a cancel button for the measurement execution process
- [x] #59
- [x] #60

### Wishlist

- [ ] Add time timestamp for each data point. Different images have different time intervals. 
- [ ] Description of functions that will be applied and in which order, similar to a recipe
